"""
URL configuration for pngjewellers project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from website import views
from adminpanel import views as adminp

urlpatterns = [
    path("",views.index),
    path("nav/",views.nav),
    path("footer/",views.footer),
    path("all_jewellery/",views.all_jewellery),
    path("Diamond/",views.Diamond),
    path("investors/",views.investors),
    path("bullions/",views.bullions),
    path("Arrival_goldjewellery/",views.Arrival_goldjewellery),
    path("Mangalsutra_Mahaotsave/",views.Mangalsutra_Mahaotsave),
    path("EIINA/",views.EIINA),
    path("Necklace_Mahotsav/",views.Necklace_Mahotsav),
    path("diamond_diwalisale/",views.diamond_diwalisale),
    path("swarajya_collecations/",views.swarajya_collecations),
    path("saptam_collecation/",views.saptam_collecation),
    path("Aarya/",views.Aarya),
    path("zodias/",views.zodias),
    path("color_stone/",views.color_stone),
    path("police_polki/",views.police_polki),
    path("sui_daga/",views.sui_daga),
    path("studs/",views.studs),
    path("Trimurtisilver_coins/",views.Trimurtisilver_coins),
    path("Trendy_mo_d_mangalsutra/",views.Trendy_mo_d_mangalsutra),
    path("slive_ganesha_coin/",views.sliver_ganesha_coin),
    path("pure_sliver_chip/",views.pure_sliver_chip),
    path("png/",views.png),
    path("office_wear/",views.office_wear),
    path("mean_studs/",views.mean_studs),
    path("laxmi_sliver_coin/",views.laxmi_sliver_coin),
    path("kids_bracelets/",views.kids_bracelets),
    path("HoopsandHuggies/",views.HoopsandHuggies),
    path("GoldParty_wear/",views.GoldParty_wear),
    path("Goldjhumka/",views.Goldjhumka),
    path("Goldrops_and_danglers/",views.Goldrops_and_danglers),
    path("Gold_vedhani/",views.Gold_vedhani),
    path("Gold_plain/",views.Gold_plain),
    path("Gold_laxmi_shree/",views.Gold_laxmi_shree),
    path("Gold_kids_earrings/",views.Gold_kids_earrings),
    path("Gold_daily_wear/",views.Gold_daily_wear),
    path("DropsandDangless/",views.DropsandDangless),
    path("DimondNecklasLarient/",views.DimondNecklasLarient),
    path("Diamondrings_dailywear/",views.Diamondrings_dailywear),
    path("Diamondrings_bands/",views.Diamondrings_bands),
    path("Diamond_short_necklaces/",views.Diamond_short_necklaces),
    path("Diamond_religious_pendant/",views.Diamond_religious_pendant),
    path("Diamond_nosepin/",views.Diamond_nosepin),
    path("Diamond_kurta_buttons/",views.Diamond_kurta_buttons),
    path("Diamond_hearte_pendant/",views.Diamond_hearte_pendant),
    path("Diamond_engagement_rings/",views.Diamond_engagement_rings),
    path("Diamond_cufflink/",views.Diamond_cufflink),
    path("Diamond_casual_rings/",views.Diamond_casual_rings),
    path("Diamond_partyWear/",views.Diamond_partyWear),
    path("Daily_wear/",views.Daily_wear),
    # path("Dai_Fashion_Ring/",views.Dai_Fashion_Ring),
    path("collection/",views.collection),
    path("Bangles_Flexible_Bracel/",views.Bangles_Flexible_Bracel),
    path("Dai_Fashion_Ring/",views.Dai_Fashion_Ring),

    path("Pj_Franchise/",views.Pj_Franchise),
    path("Store_Locator/",views.Store_Locator),
    path("login/",views.login),
    path("signup/",views.signup),

    path("save_Pj_Franchise/",views.save_Pj_Franchise),


    
    # adminpanel urls
    path('adminpanel/',adminp.login_view),
    path('admin/dashbord/',adminp.dashbord),
    # path('Profile/',adminp.Profile),
    path('admin/forgot_password/', adminp.forgot_password_view),



    
    # adminpanel urls
    # path("adminpanel/",adminp.admin_index),
    # path("admin/Dashbord/",adminp.Dashbord),
    path("admin/Navbar/",adminp.Navbar),
    path("admin/Footer/",adminp.Footer),
    path("admin/Jewellery/",adminp.Jewellery),
    path("admin/save_jewellery/",adminp.save_jewellery),
    path("admin/Slider/",adminp.Slider),
    path("admin/save_index_Slider/",adminp.save_index_Slider),
    path("admin/Best_Slider/",adminp.Best_Slider),
    path("admin/index_bast_slider/",adminp.index_bast_slider),
    path("admin/Add_banner_img/",adminp.Add_banner_img),
    path("admin/upload_banner_img/",adminp.upload_banner_img),
    path("admin/delete_banner/",adminp.delete_banner),
    path("admin/edit_banner_img/",adminp.edit_banner_img),
    path("admin/studs_card/",adminp.studs_card),
    path("admin/studs_card_Data/",adminp.studs_card_Data),
    path("admin/delete_card_studs/",adminp.delete_card_studs),
    path("admin/edit_card_studs/",adminp.edit_card_studs),
    path("admin/edit_studs_card/",adminp.edit_studs_card),
    path("admin/studs_artical/",adminp.studs_artical),
    path("admin/studs_artica_data/",adminp.studs_artica_data),
    path("admin/delete_artical_studs/",adminp.delete_artical_studs),
    path("admin/edit_artical_studs/",adminp.edit_artical_studs),
    path("admin/edit_artical_data/",adminp.edit_artical_data),
    path("admin/Hoops_and_Huggies/",adminp.Hoops_and_Huggies),
    path("admin/HoopsBannerImg/",adminp.HoopsBannerImg),
    path("admin/Hoops_huggies_banner_img/",adminp.Hoops_huggies_banner_img),
    path("admin/delete_hoops_banner/",adminp.delete_hoops_banner),
    path("admin/Hoopscard_info/",adminp.Hoopscard_info),
    path("admin/Hoops_card_Data/",adminp.Hoops_card_Data),
    path("admin/delete_card_hoops/",adminp.delete_card_hoops),
    path("admin/edit_card__hoops/",adminp.edit_card__hoops),
    path("admin/edit_hoops_card/",adminp.edit_hoops_card),
    path("admin/hoops_articleanddescription/",adminp.hoops_articleanddescription),
    path("admin/hoops_artica_data/",adminp.hoops_artica_data),
    path("admin/delete_artical_hoops/",adminp.delete_artical_hoops),
    path("admin/edit_artical_hoops/",adminp.edit_artical_hoops),
    path("admin/hoops_edit_artical_data/",adminp.hoops_edit_artical_data),
    path("admin/Queandans_Hoops/",adminp.Queandans_Hoops),
    path("admin/hoops_question_ans/",adminp.hoops_question_ans),
    path("admin/delete_question_hoops/",adminp.delete_question_hoops),
    path("admin/edit_qusetion_ans_hoops/",adminp.edit_qusetion_ans_hoops),
    path("admin/edit_hoops_question_ans/",adminp.edit_hoops_question_ans),
    path("admin/drops_banglers/",adminp.drops_banglers),
    path("admin/DropsBannerImg/",adminp.DropsBannerImg),
    path("admin/Drops_banner_img/",adminp.Drops_banner_img),
    path("admin/delete_drops_banner/",adminp.delete_drops_banner),
    path("admin/Dropscard_info/",adminp.Dropscard_info),
    path("admin/Drops_card_Data/",adminp.Drops_card_Data),
    path("admin/delete_card_drops/",adminp.delete_card_drops),
    path("admin/edit_card__drops/",adminp.edit_card__drops),
    path("admin/edit_drops_card/",adminp.edit_drops_card),
    path("admin/Drops_articleanddescription/",adminp.Drops_articleanddescription),
    path("admin/Drops_artica_data/",adminp.Drops_artica_data),
    path("admin/delete_artical_drops/",adminp.delete_artical_drops),
    path("admin/drops_edit_artical_data/",adminp.drops_edit_artical_data),
    path("admin/edit_artical_drops/",adminp.edit_artical_drops),
    path("admin/Queandans_Drops/",adminp.Queandans_Drops),
    path("admin/Drops_question_ans/",adminp.Drops_question_ans),
    path("admin/delete_question_drops/",adminp.delete_question_drops),
    path("admin/edit_qusetion_ans_drops/",adminp.edit_qusetion_ans_drops),
    path("admin/edit_drops_question_ans/",adminp.edit_drops_question_ans),
    path("admin/Sui_Dhaga/",adminp.Sui_Dhaga),
    path("admin/sui_dhaga_card_data/",adminp.sui_dhaga_card_data),
    path("admin/delete_card_sui/",adminp.delete_card_sui),
    path("admin/Edit_sui_dhaga/",adminp.Edit_sui_dhaga),
    path("admin/edit_sui_dhaga_card/",adminp.edit_sui_dhaga_card),
    path("admin/Party_Wear/",adminp.Party_Wear),
    path("admin/party_wear_card_data/",adminp.party_wear_card_data),
    path("admin/delete_card_party_wear/",adminp.delete_card_party_wear),
    path("admin/Edit_party_wear/",adminp.Edit_party_wear),
    path("admin/party_wear_card/",adminp.party_wear_card),
    path("admin/Erings_Daily_Wear/",adminp.Erings_Daily_Wear),
    path("admin/Daily_Wear_card_data/",adminp.Daily_Wear_card_data),
    path("admin/delete_card_daily_wear/",adminp.delete_card_daily_wear),
    path("admin/Edit_daily_wear/",adminp.Edit_daily_wear),
    path("admin/Edit_daily_wear_card/",adminp.Edit_daily_wear_card),
    path("admin/Diamond_Short_Necklace/",adminp.Diamond_Short_Necklace),
    path("admin/DiamondShortNecklaces_data/",adminp.DiamondShortNecklaces_data),
    path("admin/delete_DiamondShortNecklaces/",adminp.delete_DiamondShortNecklaces),
    path("admin/Edit_Diamond_Short_Necklace/",adminp.Edit_Diamond_Short_Necklace),
    path("admin/Edit_Diamond_necklace_data/",adminp.Edit_Diamond_necklace_data),
    path("admin/Lariat_Necklace_card/",adminp.Lariat_Necklace_card),
    path("admin/Lariat_Necklaces_data/",adminp.Lariat_Necklaces_data),
    path("admin/delete_Lariat_Necklaces/",adminp.delete_Lariat_Necklaces),
    path("admin/Edit_Lariat_Necklaces/",adminp.Edit_Lariat_Necklaces),
    path("admin/edit_Lariat_Necklaces_card/",adminp.edit_Lariat_Necklaces_card),
    path("admin/Lariat_Necklace_Home/",adminp.Lariat_Necklace_Home),
    path("admin/Lariat_Necklace_article_des/",adminp.Lariat_Necklace_article_des),
    path("admin/Lariat_artical_data/",adminp.Lariat_artical_data),
    path("admin/delete_artical_lariat/",adminp.delete_artical_lariat),
    path("admin/edit_artical_lariat/",adminp.edit_artical_lariat),
    path("admin/lariat_edit_artical_data/",adminp.lariat_edit_artical_data),
    path("admin/Lariat_Necklace_Ques/",adminp.Lariat_Necklace_Ques),
    path("admin/lariat_question/",adminp.lariat_question),
    path("admin/delete_question_lariat_neck/",adminp.delete_question_lariat_neck),
    path("admin/edit_qusetion_lariat_neck/",adminp.edit_qusetion_lariat_neck),
    path("admin/edit_lariat_data/",adminp.edit_lariat_data),
    path("admin/Heart_Pendant/",adminp.Heart_Pendant),
    path("admin/HeartPendant_card_save/",adminp.HeartPendant_card_save),
    path("admin/delete_HeartPendant/",adminp.delete_HeartPendant),
    path("admin/Edit_Diamond_Heart_Pendant/",adminp.Edit_Diamond_Heart_Pendant),
    path("admin/edit_Diamond_Heart_card/",adminp.edit_Diamond_Heart_card),
    path("admin/diamond_religious_pendant/",adminp.diamond_religious_pendant),
    path("admin/religious_pendant_card_save/",adminp.religious_pendant_card_save),
    path("admin/delete_religious_pendant/",adminp.delete_religious_pendant),
    path("admin/Edit_diamond_religious_pendant/",adminp.Edit_diamond_religious_pendant),
    path("admin/edit_diamond_religious_pendant_card/",adminp.edit_diamond_religious_pendant_card),
    path("admin/Flexible_Bracelet/",adminp.Flexible_Bracelet),
    path("admin/Flexible_Bracelet_Card/",adminp.Flexible_Bracelet_Card),
    path("admin/Flexible_Bracelet_save/",adminp.Flexible_Bracelet_save),
    path("admin/delete_Flexible_Bracelet/",adminp.delete_Flexible_Bracelet),
    path("admin/Edit_Flexible_Bracelet/",adminp.Edit_Flexible_Bracelet),
    path("admin/edit_Flexible_Braceletcard/",adminp.edit_Flexible_Braceletcard),
    path("admin/Flexible_Bracelet_article_Des/",adminp.Flexible_Bracelet_article_Des),
    path("admin/Flexible_Bracelet_artical_data/",adminp.Flexible_Bracelet_artical_data),
    path("admin/delete_Flexible_Bracelet_artical/",adminp.delete_Flexible_Bracelet_artical),
    path("admin/edit_Flexible_Bracelet_artical/",adminp.edit_Flexible_Bracelet_artical),
    path("admin/edit_Flexible_Bracelet_artical_data/",adminp.edit_Flexible_Bracelet_artical_data),
    path("admin/Diamond_Cufflinks/",adminp.Diamond_Cufflinks),
    path("admin/Cufflinks_card_save/",adminp.Cufflinks_card_save),
    path("admin/delete_Cufflinks_card/",adminp.delete_Cufflinks_card),
    path("admin/Edit_Cufflinks_card/",adminp.Edit_Cufflinks_card),
    path("admin/edit_Cufflinks_card_da/",adminp.edit_Cufflinks_card_da),
    path("admin/diamond_nosepin/",adminp.diamond_nosepin),
    path("admin/nosepin_card_save/",adminp.nosepin_card_save),
    path("admin/delete_nosepin_card/",adminp.delete_nosepin_card),
    path("admin/Edit_nosepin_card/",adminp.Edit_nosepin_card),
    path("admin/edit_nosepin_card_da/",adminp.edit_nosepin_card_da),
    path("admin/Gold_PartyWear/",adminp.Gold_PartyWear),
    path("admin/Gold_party_wear_save/",adminp.Gold_party_wear_save),
    path("admin/delete_Gold_party_wear/",adminp.delete_Gold_party_wear),
    path("admin/Edit_Gold_party_wear/",adminp.Edit_Gold_party_wear),
    path("admin/edit_Gold_party_card_da/",adminp.edit_Gold_party_card_da),
    path("admin/Gold_OfficeWear/",adminp.Gold_OfficeWear),
    path("admin/Gold_Office_wear_save/",adminp.Gold_Office_wear_save),
    path("admin/delete_Gold_office_wear/",adminp.delete_Gold_office_wear),
    path("admin/Edit_Gold_office_wear/",adminp.Edit_Gold_office_wear),
    path("admin/edit_office_party_card_da/",adminp.edit_office_party_card_da),
    path("admin/Gold_dailywear/",adminp.Gold_dailywear),
    path("admin/Gold_daily_wear_save/",adminp.Gold_daily_wear_save),
    path("admin/delete_Gold_daily_wear/",adminp.delete_Gold_daily_wear),
    path("admin/Edit_Gold_daily_wear/",adminp.Edit_Gold_daily_wear),
    path("admin/edit_daily_party_card_da/",adminp.edit_daily_party_card_da),
    path("admin/Gold_Kids/",adminp.Gold_Kids),
    path("admin/Gold_kids_wear_save/",adminp.Gold_kids_wear_save),
    path("admin/delete_Gold_kids_wear/",adminp.delete_Gold_kids_wear),
    path("admin/Edit_Gold_kids_wear/",adminp.Edit_Gold_kids_wear),
    path("admin/edit_kids_card_da/",adminp.edit_kids_card_da),
    path("admin/Gold_Drops_Danglers/",adminp.Gold_Drops_Danglers),
    path("admin/Gold_DropsDanglers_wear_save/",adminp.Gold_DropsDanglers_wear_save),
    path("admin/delete_Gold_Drops_dang_wear/",adminp.delete_Gold_Drops_dang_wear),
    path("admin/Gold_Drops_Danglers/",adminp.Gold_Drops_Danglers),
    path("admin/Edit_Gold_Drops_dang_wear/",adminp.Edit_Gold_Drops_dang_wear),
    path("admin/edit_drops_dang_wear_card_data/",adminp.edit_drops_dang_wear_card_data),
    #  kru
    path("admin/Jewellery/",adminp.Jewellery),
    path("admin/save_jewellery/",adminp.save_jewellery),
    path("admin/Index_main_page/",adminp.Index_main_page),
    path("admin/Slider/",adminp.Slider),
    path("admin/save_index_Slider/",adminp.save_index_Slider),
    path("admin/delete_slider/",adminp.delete_slider),
    path("admin/Best_Slider/",adminp.Best_Slider),
    path("admin/index_bast_slider/",adminp.index_bast_slider),
    path("admin/delete_custmore/",adminp.delete_custmore),
    path("admin/index_Bestseller_Category/",adminp.index_Bestseller_Category),
    path("admin/save_index_Bestseller_Category/",adminp.save_index_Bestseller_Category),
    path("admin/delete_index_Bestseller/",adminp.delete_index_Bestseller),
    path("admin/index_Shop_Category/",adminp.index_Shop_Category),
    path("admin/save_index_Shop_Category/",adminp.save_index_Shop_Category),
    path("admin/delete_shop_Category/",adminp.delete_shop_Category),
    path("admin/index_PNG_Promises/",adminp.index_PNG_Promises),
    path("admin/save_index_bast_slider/",adminp.save_index_bast_slider),
    path("admin/delete_index_Png_Name/",adminp.delete_index_Png_Name),
    path("admin/index_video/",adminp.index_video),
    path("admin/save_index_video/",adminp.save_index_video),
    path("admin/delete_video/",adminp.delete_video),
    path("admin/PNG_Jewellers/",adminp.PNG_Jewellers),
    path("admin/index_PNG_Jewellers/",adminp.index_PNG_Jewellers),
    path("admin/delete_Png_Jewellerss/",adminp.delete_Png_Jewellerss),
    path("admin/edit_Info/",adminp.edit_Info),
    path("admin/update_info/",adminp.update_info),
    path("admin/Store_Locator/",adminp.Store_Locator),
    path("admin/index_Store_Locator/",adminp.index_Store_Locator),
    path("admin/delete_Store_Locator/",adminp.delete_Store_Locator),
    path("admin/edit_Store_Locator/",adminp.edit_Store_Locator),
    path("admin/update_edit_Store_Locator/",adminp.update_edit_Store_Locator),
    path("admin/Celebrity_Corner/",adminp.Celebrity_Corner),
    path("admin/index_Celebrity_Corner/",adminp.index_Celebrity_Corner),
    path("admin/delete_Celebrity_Corner/",adminp.delete_Celebrity_Corner),
    path("admin/Collections_Main/",adminp.Collections_Main),
    path("admin/Arrival_goldjewellery/",adminp.Arrival_goldjewellery),
    path("admin/save_Arrival_goldjewellery/",adminp.save_Arrival_goldjewellery),
    path("admin/delete_card_Arrival/",adminp.delete_card_Arrival),
    path("admin/edit_card_Arrival/",adminp.edit_card_Arrival),
    path("admin/edit_Arrival_data/",adminp.edit_Arrival_data),
    path("admin/Mangalsutra_Mahaotsave/",adminp.Mangalsutra_Mahaotsave),
    path("admin/save_Mangalsutra_Mahaotsave/",adminp.save_Mangalsutra_Mahaotsave),
    path("admin/delete_card_Mangalsutra/",adminp.delete_card_Mangalsutra),
    path("admin/edit_card_Mangalsutra/",adminp.edit_card_Mangalsutra),
    path("admin/save_edit_Mangalsutra/",adminp.save_edit_Mangalsutra),
    path("admin/EIINA/",adminp.EIINA),
    path("admin/EIINA_Slider/",adminp.EIINA_Slider),
    path("admin/upload_EIINA_banner_img/",adminp.upload_EIINA_banner_img),
    path("admin/delete_EIINA_banner/",adminp.delete_EIINA_banner),
    path("admin/EIINA_Cards/",adminp.EIINA_Cards),
    path("admin/save_EIINA_card/",adminp.save_EIINA_card),
    path("admin/delete_card_EIINA/",adminp.delete_card_EIINA),
    path("admin/edit_EIINA/",adminp.edit_EIINA),
    path("admin/save_edit_EIINA/",adminp.save_edit_EIINA),
    path("admin/Necklace_Mahotsav/",adminp.Necklace_Mahotsav),
    path("admin/save_Necklace_Mahotsavs/",adminp.save_Necklace_Mahotsavs),
    path("admin/delete_card_Necklace_Mahotsav/",adminp.delete_card_Necklace_Mahotsav),
    path("admin/edit_Necklace_Mahotsav/",adminp.edit_Necklace_Mahotsav),
    path("admin/diamond_diwalisale/",adminp.diamond_diwalisale),
    path("admin/save_diamond_diwalisale_card/",adminp.save_diamond_diwalisale_card),
    path("admin/delete_card_diamond_diwalisale/",adminp.delete_card_diamond_diwalisale),
    path("admin/edit_diamond_diwalisale/",adminp.edit_diamond_diwalisale),
    path("admin/update_diamond_diwalisale/",adminp.update_diamond_diwalisale),
    path("admin/swarajya_collecations/",adminp.swarajya_collecations),
    path("admin/collecations_swarajya_Slider/",adminp.collecations_swarajya_Slider),
    path("admin/save_collecations_swarajya_banner/",adminp.save_collecations_swarajya_banner),
    path("admin/delete_banner_collecations_swarajya_Image/",adminp.delete_banner_collecations_swarajya_Image),
    path("admin/collecations_swarajya_Cards/",adminp.collecations_swarajya_Cards),
    path("admin/save_ollecations_swarajya_card/",adminp.save_ollecations_swarajya_card),
    path("admin/delete_card_ollecations_swarajya/",adminp.delete_card_ollecations_swarajya),
    path("admin/edit_ollecations_swarajya/",adminp.edit_ollecations_swarajya),
    path("admin/Update_Sllecations_swarajya/",adminp.Update_Sllecations_swarajya),
    path("admin/saptam_collecation/",adminp.saptam_collecation),
    path("admin/Saptam_Collecation_Slider/",adminp.Saptam_Collecation_Slider),
    path("admin/upload_banner_Saptam_Collecation_img/",adminp.upload_banner_Saptam_Collecation_img),
    path("admin/Saptam_Collecation_Cards/",adminp.Saptam_Collecation_Cards),
    path("admin/save_Saptam_Collection/",adminp.save_Saptam_Collection),
    path("admin/delete_card_Saptam_Collection/",adminp.delete_card_Saptam_Collection),
    path("admin/edit_Saptam_Collection/",adminp.edit_Saptam_Collection),
    path("admin/Update_Saptam_Collection/",adminp.Update_Saptam_Collection),
    path("admin/Aarya/",adminp.Aarya),
    path("admin/save_Aarya_card/",adminp.save_Aarya_card),
    path("admin/delete_card_Aarya/",adminp.delete_card_Aarya),
    path("admin/edit_Aarya/",adminp.edit_Aarya),
    path("admin/Update_Aarya/",adminp.Update_Aarya),
    path("admin/zodias/",adminp.zodias),
    path("admin/save_zodias_card/",adminp.save_zodias_card),
    path("admin/delete_card_zodias/",adminp.delete_card_zodias),
    path("admin/edit_zodias/",adminp.edit_zodias),
    path("admin/Update_Zodias/",adminp.Update_Zodias),
    path("admin/color_stone/",adminp.color_stone),
    path("admin/save_Colour_Stones_card/",adminp.save_Colour_Stones_card),
    path("admin/delete_card_Colour_Stones/",adminp.delete_card_Colour_Stones),
    path("admin/edit_Colour_Stones/",adminp.edit_Colour_Stones),
    path("admin/Update_Colour_Stones/",adminp.Update_Colour_Stones),
    path("admin/police_polki/",adminp.police_polki),
    path("admin/Police_Polki_Slider/",adminp.Police_Polki_Slider),
    path("admin/upload_banner_Police_Polki/",adminp.upload_banner_Police_Polki),
    path("admin/delete_banner_Police_Polki/",adminp.delete_banner_Police_Polki),
    path("admin/Police_Polki_Cards/",adminp.Police_Polki_Cards),
    path("admin/save_Police_Polki_Cards/",adminp.save_Police_Polki_Cards),
    path("admin/delete_card_PolicCard/",adminp.delete_card_PolicCard),
    path("admin/edit_card_PolicCard/",adminp.edit_card_PolicCard),
    path("admin/edit_PolicCard_card/",adminp.edit_PolicCard_card),
    path("admin/Trendy_mo_d_mangalsutra/",adminp.Trendy_mo_d_mangalsutra),
    path("admin/Drops_mangalsutraCard/",adminp.Drops_mangalsutraCard),
    path("admin/save_card_mangalsutra/",adminp.save_card_mangalsutra),
    path("admin/delete_card_mangalsutra/",adminp.delete_card_mangalsutra),
    path("admin/edit_card_mangalsutra/",adminp.edit_card_mangalsutra),
    path("admin/edit_Diamond_Drops_mangalsutraCard/",adminp.edit_Diamond_Drops_mangalsutraCard),
    path("admin/Drop_mangalsutra_text/",adminp.Drop_mangalsutra_text),
    path("admin/save_card_mangalsutras/",adminp.save_card_mangalsutras),
    path("admin/delete_mangalsutra/",adminp.delete_mangalsutra),
    path("admin/edit_mangalsutra/",adminp.edit_mangalsutra),
    path("admin/edit_Diamond_mangalsutra/",adminp.edit_Diamond_mangalsutra),
    path("admin/Kurta_Button/",adminp.Kurta_Button),
    path("admin/Kurta_page_card_Data/",adminp.Kurta_page_card_Data),
    path("admin/delete_card_Kurta/",adminp.delete_card_Kurta),
    path("admin/edit_card_Kurta/",adminp.edit_card_Kurta),
    path("admin/edit_Diamond_KurtaPage/",adminp.edit_Diamond_KurtaPage),
    path("admin/Gold_Jhumkas/",adminp.Gold_Jhumkas),
    path("admin/edit_card_Gold_GoldBracelets/",adminp.edit_card_Gold_GoldBracelets),
    path("admin/Gold_Jhumkas_card_Data/",adminp.Gold_Jhumkas_card_Data),
    path("admin/delete_card_Gold_Jhumkas/",adminp.delete_card_Gold_Jhumkas),
    path("admin/delete_card_Gold_Jhumkas/",adminp.delete_card_Gold_Jhumkas),
    path("admin/edit_card_Gold_Jhumkas/",adminp.edit_card_Gold_Jhumkas),
    path("admin/edit_Diamond_Gold_Jhumkas/",adminp.edit_Diamond_Gold_Jhumkas),
    path("admin/Gold_Menstuds/",adminp.Gold_Menstuds),
    path("admin/Gold_Menstuds_card_Data/",adminp.Gold_Menstuds_card_Data),
    path("admin/delete_card_Gold_Menstuds/",adminp.delete_card_Gold_Menstuds),
    path("admin/edit_card_Gold_Menstuds/",adminp.edit_card_Gold_Menstuds),
    path("admin/edit_Diamond_Gold_Menstuds/",adminp.edit_Diamond_Gold_Menstuds),
    path("admin/Gold_GoldBracelets/",adminp.Gold_GoldBracelets),
    path("admin/Gold_GoldBracelets_card_Data/",adminp.Gold_GoldBracelets_card_Data),
    path("admin/delete_card_Gold_GoldBracelets/",adminp.delete_card_Gold_GoldBracelets),
    path("admin/edit_card_Gold_GoldBracelets/",adminp.edit_card_Gold_GoldBracelets),
    path("admin/edit_Diamond_GoldBracelets/",adminp.edit_Diamond_GoldBracelets),
    path("admin/Gold_vedhani/",adminp.Gold_vedhani),
    path("admin/Gold_vedhani_card_Data/",adminp.Gold_vedhani_card_Data),
    path("admin/delete_card_Gold_vedhani/",adminp.delete_card_Gold_vedhani),
    path("admin/edit_card_Gold_vedhani/",adminp.edit_card_Gold_vedhani),
    path("admin/edit_Diamond_Gold_vedhani/",adminp.edit_Diamond_Gold_vedhani),
    path("admin/Gold_plain/",adminp.Gold_plain),
    path("admin/Gold_plain_wear_save/",adminp.Gold_plain_wear_save),
    path("admin/delete_Gold_plain_wear/",adminp.delete_Gold_plain_wear),
    path("admin/Edit_Gold_plain_wear/",adminp.Edit_Gold_plain_wear),
    path("admin/edit_Gold_plain_card_da/",adminp.edit_Gold_plain_card_da),
    path("admin/PNG/",adminp.PNG),
    path("admin/Gold_PNG_wear_save/",adminp.Gold_PNG_wear_save),
    path("admin/delete_Gold_png_wear/",adminp.delete_Gold_png_wear),
    path("admin/Edit_Gold_png_wear/",adminp.Edit_Gold_png_wear),
    path("admin/edit_Gold_png_card_da/",adminp.edit_Gold_png_card_da),
    path("admin/delete_slider/",adminp.delete_slider),
    path("admin/edit_jewellery/",adminp.edit_jewellery),
    path("admin/Update_edit_jewellery/",adminp.Update_edit_jewellery),
    path("admin/delete_jewellery/",adminp.delete_jewellery),
    path("admin/delete_bast_slider/",adminp.delete_bast_slider),
    path("admin/edit_bast_slider/",adminp.edit_bast_slider),
    path("admin/update_info_bast_slider/",adminp.update_info_bast_slider),
    path("admin/edit_index_Png_Name/",adminp.edit_index_Png_Name),
    path("admin/Update_edit_index_Png_Name/",adminp.Update_edit_index_Png_Name),
    path("admin/edit_Celebrity_Corner/",adminp.edit_Celebrity_Corner),
    path("admin/Gold_laxmi_shree/",adminp.Gold_laxmi_shree),
    path("admin/Save_Gold_laxmi_shree/",adminp.Save_Gold_laxmi_shree),
    path("admin/delete_card_Gold_laxmi/",adminp.delete_card_Gold_laxmi),
    path("admin/edit_Gold_laxmi/",adminp.edit_Gold_laxmi),
    path("admin/update_Gold_laxmi/",adminp.update_Gold_laxmi),
    path("admin/Studs_Erings/",adminp.Studs_Erings),
    # karan
    path("admin/Diamondrings_bands/",adminp.Diamondrings_bands),
    path("admin/save_Diamondrings/",adminp.save_Diamondrings),
    path("admin/Diamond_engagement_ring/",adminp.Diamond_engagement_ring),
    path("admin/save_engagement_ring/",adminp.save_engagement_ring),
    path("admin/Diamond_fashion_ring/",adminp.Diamond_fashion_ring),
    path("admin/save_fashion_ring/",adminp.save_fashion_ring),
    path("admin/Diamond_casual_ring/",adminp.Diamond_casual_ring),
    path("admin/save_casual_ring/",adminp.save_casual_ring),
    # delete url #
    path("admin/delete_casual_ring/",adminp.delete_casual_ring),
    path("admin/delete_engagement_ring/",adminp.delete_engagement_ring),
    path("admin/delete_fashion_ring/",adminp.delete_fashion_ring),
    path("admin/delete_bands_ring/",adminp.delete_bands_ring),
    # edit url#
    path("admin/edit_bands_ring/",adminp.edit_bands_ring),
    path("admin/update_Diamondrings/",adminp.update_Diamondrings),
    path("admin/edit_engagement_ring/", adminp.edit_engagement_ring),
    path("admin/update_engagement/", adminp.update_engagement),
    path("admin/edit_fashion_ring/",adminp.edit_fashion_ring),
    path("admin/update_fashion/",adminp.update_fashion),
    path('admin/edit_casual_ring/<int:ring_id>/',adminp.edit_casual_ring),

    #   Akshay Bodkhe
# start gold_vedhani
    path("admin/gold_vedhani/",adminp.gold_vedhani),
    path("admin/save_gold_vedhani/",adminp.save_gold_vedhani),
    path("admin/edit_gold_vedhani/",adminp.edit_gold_vedhani),
    path("admin/update_gold_vedhani/",adminp.update_gold_vedhani),
    path("admin/delete_gold_vedhani/",adminp.delete_gold_vedhani),
# end gold_vedhani
 

# start gold_plain
    path("admin/gold_plain/",adminp.gold_plain),
    path("admin/save_gold_plain/",adminp.save_gold_plain),
    path("admin/edit_gold_plain/",adminp.edit_gold_plain),
    path("admin/update_gold_plain/",adminp.update_gold_plain),
    path("admin/delete_gold_plain/",adminp.delete_gold_plain),
# end gold_plain


# start gold_laxmi_shree
    path("admin/gold_laxmi_shree/",adminp.gold_laxmi_shree),
    path("admin/save_laxmi_shree/",adminp.save_laxmi_shree),
    path("admin/edit_gold_laxmi_shree/",adminp.edit_gold_laxmi_shree),
    path("admin/update_laxmi_shree/",adminp.update_laxmi_shree),
    path("admin/delete_gold_laxmi_shree/",adminp.delete_gold_laxmi_shree),
# end gold_laxmi_shree

# start PNG
    path("admin/png/",adminp.png),
    path("admin/save_gold_png/",adminp.save_gold_png),
    path("admin/edit_gold_png/",adminp.edit_gold_png),
    path("admin/update_gold_png/",adminp.update_gold_png),
    path("admin/delete_gold_png/",adminp.delete_gold_png),
# end PNG

# start silver_ganesh_coin
    path("admin/silver_ganesh_coin/",adminp.silver_ganesh_coin),
    path("admin/save_silver_ganesh/",adminp.save_silver_ganesh),
    path("admin/edit_silver_ganesh/",adminp.edit_silver_ganesh),
    path("admin/update_silver_ganesh/",adminp.update_silver_ganesh),
    path("admin/delete_silver_ganesh/",adminp.delete_silver_ganesh),
# end silver_ganesh_coin

# start pure_silver_chip
    path("admin/pure_silver_chip/",adminp.pure_silver_chip),
    path("admin/save_silver_chip/",adminp.save_silver_chip),
    path("admin/edit_silver_chip/",adminp.edit_silver_chip),
    path("admin/update_silver_chip/",adminp.update_silver_chip),
    path("admin/delete_silver_chip/",adminp.delete_silver_chip),
# end pure_silver_chip

# start silver_laxmi
    path("admin/silver_laxmi/",adminp.silver_laxmi),
    path("admin/save_silver_laxmi/",adminp.save_silver_laxmi),
    path("admin/edit_silver_laxmi/",adminp.edit_silver_laxmi),
    path("admin/update_silver_laxmi/",adminp.update_silver_laxmi),
    path("admin/delete_silver_laxmi/",adminp.delete_silver_laxmi),
# end silver_laxmi

# start investors_image
    path("admin/investors_image/",adminp.investors_image),
    path("admin/save_investors/",adminp.save_investors),
    path("admin/edit_investors_image/",adminp.edit_investors_image),
    path("admin/update_investors/",adminp.update_investors),
    path("admin/delete_investors_image/",adminp.delete_investors_image),
# end investors_image

# start investors_contacts
    path("admin/investors_contacts/",adminp.investors_contacts),
    path("admin/save_investor_contacts/",adminp.save_investor_contacts),
    path("admin/edit_investor_contacts/",adminp.edit_investor_contacts),
    path("admin/update_investor_contacts/",adminp.update_investor_contacts),
    path("admin/delete_investor_contacts/",adminp.delete_investor_contacts),
# end investors_contacts

# start annual_reports
    path("admin/annual_reports/",adminp.annual_reports),
    path("admin/save_annual_report/",adminp.save_annual_report),
    path("admin/delete_annual_report/",adminp.delete_annual_report),
# end annual_reports

# start policies
    path("admin/corporate_policies/",adminp.corporate_policies),
    path("admin/save_policies/",adminp.save_policies),
    path("admin/delete_policies/",adminp.delete_policies),
# end policies

# start corporate_governance
    path("admin/corporate_governance/",adminp.corporate_governance),
    path("admin/save_corporate/",adminp.save_corporate),
    path("admin/delete_corporate/",adminp.delete_corporate),
# end corporate_governance

# start group_gompanies
    path("admin/group_gompanies/",adminp.group_gompanies),
    path("admin/save_group/",adminp.save_group),
    path("admin/delete_group_companies/",adminp.delete_group_companies),
# end group_gompanies

# start fixed_deposit
    path("admin/fixed_deposit/",adminp.fixed_deposit),
    path("admin/save_fixed_deposit/",adminp.save_fixed_deposit),
    path("admin/delete_fixed_deposit/",adminp.delete_fixed_deposit),
# end fixed_deposit

# start financial_results
    path("admin/financial_results/",adminp.financial_results),
    path("admin/save_financial_results/",adminp.save_financial_results),
    path("admin/delete_financial_results/",adminp.delete_financial_results),
# end financial_results

# start disclosure_under_regulation
    path("admin/disclosure_under_regulation/",adminp.disclosure_under_regulation),
    path("admin/save_disclosure/",adminp.save_disclosure),
    path("admin/delete_disclosure/",adminp.delete_disclosure),
# end disclosure_under_regulation

# start shareholding_pattern
    path("admin/shareholding_pattern/",adminp.shareholding_pattern),
    path("admin/save_shareholding_pattern/",adminp.save_shareholding_pattern),
    path("admin/delete_shareholding_pattern/",adminp.delete_shareholding_pattern),
# end shareholding_pattern

# start stock_exchange
    path("admin/stock_exchange/",adminp.stock_exchange),
    path("admin/save_stock_exchange/",adminp.save_stock_exchange),
    path("admin/delete_stock_exchange/",adminp.delete_stock_exchange),
# end stock_exchange

# start notice_outcome
    path("admin/notice_outcome/",adminp.notice_outcome),
    path("admin/save_notice_outcome/",adminp.save_notice_outcome),
    path("admin/delete_notice_outcome/",adminp.delete_notice_outcome),
# end notice_outcome

# start Press Release
    path("admin/press_release/",adminp.press_release),
    path("admin/save_press_release/",adminp.save_press_release),
    path("admin/delete_press_release/",adminp.delete_press_release),
# end Press Release

# start corporate_social
    path("admin/corporate_social/",adminp.corporate_social),
    path("admin/save_corporate_social/",adminp.save_corporate_social),
    path("admin/delete_corporate_social/",adminp.delete_corporate_social),
# end corporate_social

# start reports
    path("admin/reports/",adminp.reports),
    path("admin/save_reports/",adminp.save_reports),
    path("admin/delete_reports/",adminp.delete_reports),
# end reports

# start Risk policies1
    path("admin/policies1/",adminp.policies1),
    path("admin/save_policies1/",adminp.save_policies1),
    path("admin/delete_policies1/",adminp.delete_policies1),
# end Risk policies1

# start post_policies
    path("admin/post_policies/",adminp.post_policies),
    path("admin/save_post_policies/",adminp.save_post_policies),
    path("admin/delete_post_policies/",adminp.delete_post_policies),
# end post_policies

# start material_documents
    path("admin/material_documents/",adminp.material_documents),
    path("admin/save_material_documents/",adminp.save_material_documents),
    path("admin/delete_material_documents/",adminp.delete_material_documents),
# end material_documents

# start ipo_documents
    path("admin/ipo_documents/",adminp.ipo_documents),
    path("admin/save_ipo_documents/",adminp.save_ipo_documents),
    path("admin/delete_ipo_documents/",adminp.delete_ipo_documents),
# end ipo_documents
    
    path("admin/Profile/",adminp.Profile),
    path("admin/Pj_Franchisess/",adminp.Pj_Franchisess),
    path("admin/Edit_Pj_Franchisess/",adminp.Edit_Pj_Franchisess),
    path("admin/update_pg_franchiess/",adminp.update_pg_franchiess),
    path("admin/Silver_Coin/",adminp.Silver_Coin),

    path("admin/edit_Slider/",adminp.edit_Slider),
    path("admin/update_Slider/",adminp.update_Slider),



    path("Contact/",views.Contact),
    path("contest_programs/",views.contest_programs),

]