# Generated by Django 5.0.7 on 2025-01-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=10)),
                ('email_address', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('occupation', models.CharField(max_length=1000)),
                ('City_name', models.CharField(max_length=100)),
                ('pincodes', models.CharField(max_length=100)),
                ('investment', models.CharField(max_length=100)),
            ],
        ),
    ]
