# Generated by Django 5.0.7 on 2025-01-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jewellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_jewellery', models.CharField(max_length=100)),
                ('price_jewellery', models.CharField(max_length=50)),
                ('description_jewellery', models.CharField(max_length=100)),
            ],
        ),
    ]
