# Generated by Django 5.0.7 on 2025-01-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewellery',
            name='image_jewellery',
            field=models.ImageField(upload_to='jewellery_images/'),
        ),
    ]
