# Generated by Django 5.0.7 on 2025-01-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_jewellery_image_jewellery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewellery',
            name='image_jewellery',
            field=models.ImageField(upload_to='static/admin/img/'),
        ),
    ]
