# Generated by Django 5.0.7 on 2025-01-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_alter_jewellery_image_jewellery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_index_Slider', models.ImageField(upload_to='static/admin/img/')),
            ],
        ),
    ]
