# Generated by Django 5.0.7 on 2025-01-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_index_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_Bast_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bast_Slider_imgase', models.ImageField(upload_to='static/admin/img/')),
                ('bast_Slider_Name', models.CharField(max_length=50)),
                ('bast_Slider_Description', models.CharField(max_length=50)),
                ('bast_Slider_Price', models.CharField(max_length=50)),
            ],
        ),
    ]
