# Generated by Django 5.0.7 on 2025-01-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_index_bast_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_Studs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img', models.ImageField(upload_to='static/admin/img')),
                ('title', models.CharField(max_length=50)),
                ('titleDescription', models.CharField(max_length=100)),
                ('product_img', models.ImageField(upload_to='static/admin/img')),
                ('product_title', models.CharField(max_length=50)),
                ('Product_Latest_Price', models.IntegerField()),
                ('Product_Previous_Price', models.IntegerField()),
                ('Article_Heading', models.CharField(max_length=100)),
                ('articleDescription', models.CharField(max_length=300)),
            ],
        ),
    ]
