# Generated by Django 5.0.7 on 2025-01-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_d_studs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_studs',
            old_name='titleDescription',
            new_name='Title_Description',
        ),
    ]
