# Generated by Django 5.0.7 on 2025-01-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_rename_titledescription_d_studs_title_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studs_banner_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerImage', models.ImageField(upload_to='static/admin/img/')),
            ],
        ),
        migrations.DeleteModel(
            name='D_Studs',
        ),
    ]
