# Generated by Django 5.0.7 on 2025-01-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_studs_banner_img_delete_d_studs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studs_cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_description', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='static/admin/img')),
                ('image_title', models.CharField(max_length=50)),
                ('latest_price', models.IntegerField()),
                ('old_price', models.IntegerField()),
            ],
        ),
    ]
