# Generated by Django 5.0.7 on 2025-01-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_studs_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studs_cards',
            name='title',
        ),
        migrations.RemoveField(
            model_name='studs_cards',
            name='title_description',
        ),
    ]
