# Generated by Django 5.0.7 on 2025-01-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_remove_studs_cards_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studs_artical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleHeading', models.CharField(max_length=100)),
                ('articleDescription', models.CharField(max_length=1000)),
            ],
        ),
    ]
