# Generated by Django 5.0.7 on 2025-01-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_studs_artical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hoops_Huggies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hoops_bannerImage', models.ImageField(upload_to='static/admin/img')),
            ],
        ),
    ]
