# Generated by Django 5.0.7 on 2025-01-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_hoops_article_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hoops_Question_Ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
    ]
