# Generated by Django 5.0.7 on 2025-01-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_remove_hoops_question_ans_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drops_Banner_img1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drops_bannerImage', models.ImageField(upload_to='static/admin/img')),
            ],
        ),
    ]
