# Generated by Django 5.0.7 on 2025-01-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_drops_article_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drops_Question_Ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='hoops_question_ans',
            name='Question',
            field=models.CharField(max_length=1000),
        ),
    ]
