# Generated by Django 5.0.7 on 2025-01-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0025_lariat_necklaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lari_Neck_Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleHeading', models.CharField(max_length=200)),
                ('articleDescription', models.CharField(max_length=1000)),
            ],
        ),
    ]
