# Generated by Django 5.0.7 on 2025-01-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_lari_neck_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lariant_Que',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=1000)),
            ],
        ),
    ]
