# Generated by Django 5.0.7 on 2025-01-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0029_religious_pend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flexible_Brac_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImage', models.ImageField(upload_to='static/admin/img')),
                ('productTitle', models.CharField(max_length=200)),
                ('latestPrice', models.IntegerField()),
                ('oldPrice', models.IntegerField()),
            ],
        ),
    ]
