# Generated by Django 5.0.7 on 2025-01-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0038_gold_drops_danglers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aaryas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aarya_image', models.ImageField(upload_to='static/admin/img/')),
                ('Aarya_Description', models.CharField(max_length=1000)),
                ('Aarya_Latest_price', models.CharField(max_length=100)),
                ('Aarya_old_price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Arrival_Goldjewellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arrival_goldjewellery_image', models.ImageField(upload_to='static/admin/img/')),
                ('image_Description', models.CharField(max_length=1000)),
                ('Arrival_goldjewellery_price', models.CharField(max_length=100)),
                ('Arrival_goldjewellery_old_price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bestseller_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_Bestseller_Category_img', models.ImageField(upload_to='static/admin/img/')),
            ],
        ),
        migrations.CreateModel(
            name='Collecations_Swarajya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collecations_swarajya_Image', models.ImageField(upload_to='static/admin/img/')),
            ],
        ),
        migrations.CreateModel(
            name='Colour_Stones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Colour_Stones_image', models.ImageField(upload_to='static/admin/img/')),
                ('Colour_Stones_Description', models.CharField(max_length=1000)),
                ('Colour_Stones_Latest_price', models.CharField(max_length=100)),
                ('Colour_Stones_old_price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diamond_Diwalisale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamond_diwalisale_image', models.ImageField(upload_to='static/admin/img/')),
                ('diamond_diwalisale_Description', models.CharField(max_length=1000)),
                ('diamond_diwalisale_Latest_price', models.CharField(max_length=100)),
                ('diamond_diwalisale_old_price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EIINA_Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EIINA_bannerImage', models.ImageField(upload_to='static/admin/img/')),
            ],
        ),
        migrations.CreateModel(
            name='EIINA_CARDs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EIINA_image', models.ImageField(upload_to='static/admin/img/')),
                ('EIINA_Description', models.CharField(max_length=1000)),
                ('EIINA_Latest_price', models.CharField(max_length=100)),
                ('EIINA_old_price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='index_Celebrity_Corner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Celebrity_Corner_img', models.ImageField(upload_to='static/admin/img/')),
                ('Celebrity_Corner_img1', models.ImageField(upload_to='static/admin/img/')),
                ('Celebrity_Corner_img2', models.ImageField(upload_to='static/admin/img/')),
                ('Celebrity_Corner_img3', models.ImageField(upload_to='static/admin/img/')),
                ('Celebrity_Corner_Heiding', models.CharField(max_length=50)),
                ('Celebrity_Corner_Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='index_Store_Locator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_Locator_img', models.ImageField(upload_to='static/admin/img/')),
                ('Store_Locator_Heiding', models.CharField(max_length=50)),
                ('Store_Locator_Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mangalsutra_mahaotsave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mangalsutra_Mahaotsave_image', models.ImageField(upload_to='static/admin/img/')),
                ('Mangalsutra_Mahaotsave_Description', models.CharField(max_length=1000)),
                ('Mangalsutra_Mahaotsave_price', models.CharField(max_length=100)),
                ('Mangalsutra_Mahaotsave_old_price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Necklace_mahotsav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Necklace_Mahotsav_image', models.ImageField(upload_to='static/admin/img/')),
                ('Necklace_Mahotsav_Description', models.CharField(max_length=1000)),
                ('Necklace_Mahotsav_Latest_price', models.CharField(max_length=100)),
                ('Necklace_Mahotsav_old_price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Png_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_Png', models.ImageField(upload_to='static/admin/img/')),
                ('index_Png_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Png_JEWELLERS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PNG_Jewellerss', models.ImageField(upload_to='static/admin/img/')),
                ('PNG_Jewellers_text', models.CharField(max_length=50)),
                ('index_Heiding', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Police_Polki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_Image_Police_Polki', models.ImageField(upload_to='static/admin/img/')),
            ],
        ),
        migrations.CreateModel(
            name='Police_Polki_Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Police_Polki_image', models.ImageField(upload_to='static/admin/img/')),
                ('Police_Polki_Description', models.CharField(max_length=1000)),
                ('Police_Polki_price', models.CharField(max_length=100)),
                ('Police_Polki_old_price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Saptam_Collecation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Saptam_Collecation_bannerImage', models.ImageField(upload_to='static/admin/img/')),
            ],
        ),
        migrations.CreateModel(
            name='Saptam_Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Saptam_Collection_image', models.ImageField(upload_to='static/admin/img/')),
                ('Saptam_Collection_Description', models.CharField(max_length=1000)),
                ('Saptam_Collection_Latest_price', models.CharField(max_length=100)),
                ('Saptam_Collection_old_price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Save_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bast_Slider_video', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_Shop_Category', models.ImageField(upload_to='static/admin/img/')),
                ('Name_Shop_Category', models.CharField(max_length=50)),
                ('description_Shop_Category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sllecations_swarajya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ollecations_swarajya_image', models.ImageField(upload_to='static/admin/img/')),
                ('ollecations_swarajya_Description', models.CharField(max_length=1000)),
                ('ollecations_swarajya_Latest_price', models.CharField(max_length=100)),
                ('ollecations_swarajya_old_price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zodias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zodias_image', models.ImageField(upload_to='static/admin/img/')),
                ('zodias_Description', models.CharField(max_length=1000)),
                ('zodias_Latest_price', models.CharField(max_length=100)),
                ('zodias_old_price', models.CharField(max_length=100)),
            ],
        ),
    ]
