# Generated by Django 5.0.7 on 2025-01-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0042_goldpng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gold_laxmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gold_laxmi_image', models.ImageField(upload_to='static/admin/img')),
                ('Gold_laxmi_Description', models.CharField(max_length=200)),
                ('Gold_laxmi_Latest_price', models.IntegerField()),
            ],
        ),
    ]
