# Generated by Django 5.0.7 on 2025-01-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0043_gold_laxmi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casual_ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casualring_image', models.ImageField(upload_to='static/admin/img')),
                ('casualring_price', models.CharField(max_length=50)),
                ('casualring_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Diamond_engagement_ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enagagement_image', models.ImageField(upload_to='static/admin/img')),
                ('enagagement_price', models.CharField(max_length=50)),
                ('enagagement_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Diamond_fashion_ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_fashion', models.ImageField(upload_to='static/admin/img')),
                ('price_fashion', models.CharField(max_length=50)),
                ('text_fashion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Diamondrings_bands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimaonderings_image', models.ImageField(upload_to='static/admin/img')),
                ('diamondrings_pricce', models.CharField(max_length=50)),
                ('diamondrings_text', models.CharField(max_length=200)),
            ],
        ),
    ]
