# Generated by Django 5.0.1 on 2025-01-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0044_casual_ring_diamond_engagement_ring_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gold_Laxmi_Shree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_laxmi_shree_image', models.ImageField(upload_to='static/admin/img')),
                ('gold_laxmi_shree_price', models.CharField(max_length=50)),
                ('gold_laxmi_shree_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gold_Plain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_plain_image', models.ImageField(upload_to='static/admin/img')),
                ('gold_plain_price', models.CharField(max_length=50)),
                ('gold_plain_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gold_PNG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_png_image', models.ImageField(upload_to='static/admin/img')),
                ('gold_png_price', models.CharField(max_length=50)),
                ('gold_png_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gold_Vedhani1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_vedhani_image', models.ImageField(upload_to='static/admin/img')),
                ('gold_vedhani_price', models.CharField(max_length=50)),
                ('gold_vedhani_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Investors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investors_image', models.ImageField(upload_to='static/admin/img')),
            ],
        ),
        migrations.CreateModel(
            name='Investors_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_mobile', models.CharField(max_length=20)),
                ('contact_email', models.CharField(max_length=200)),
                ('contact_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Silver_Chip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silver_chip_image', models.ImageField(upload_to='static/admin/img')),
                ('silver_chip_price', models.CharField(max_length=50)),
                ('silver_chip_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Silver_Ganesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silver_ganesh_image', models.ImageField(upload_to='static/admin/img')),
                ('silver_ganesh_price', models.CharField(max_length=50)),
                ('silver_ganesh_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Silver_Laxmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silver_laxmi_image', models.ImageField(upload_to='static/admin/img')),
                ('silver_laxmi_price', models.CharField(max_length=50)),
                ('silver_laxmi_text', models.CharField(max_length=200)),
            ],
        ),
    ]
