# Generated by Django 5.0.1 on 2025-01-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0045_gold_laxmi_shree_gold_plain_gold_png_gold_vedhani1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annual_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_report', models.FileField(upload_to='static/admin/img')),
            ],
        ),
    ]
