# Generated by Django 5.0.1 on 2025-01-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0046_annual_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualReport1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_report', models.FileField(upload_to='static/admin/img')),
                ('annual_report_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Annual_Report',
        ),
    ]
