# Generated by Django 5.0.1 on 2025-01-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0047_annualreport1_delete_annual_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policies_report', models.FileField(upload_to='static/admin/img')),
                ('policies_report_details', models.CharField(max_length=100)),
            ],
        ),
    ]
