# Generated by Django 5.0.1 on 2025-01-13 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0048_policies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policies',
            old_name='policies_report',
            new_name='policies',
        ),
        migrations.RenameField(
            model_name='policies',
            old_name='policies_report_details',
            new_name='policies_details',
        ),
    ]
