# Generated by Django 5.0.1 on 2025-01-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0049_rename_policies_report_policies_policies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate', models.FileField(upload_to='static/admin/img')),
                ('corporate_details', models.CharField(max_length=100)),
            ],
        ),
    ]
