# Generated by Django 5.0.1 on 2025-01-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0051_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixed_Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_deposit', models.FileField(upload_to='static/admin/img')),
                ('fixed_deposit_details', models.CharField(max_length=100)),
            ],
        ),
    ]
