# Generated by Django 5.0.1 on 2025-01-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0053_financial_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disclosure_Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclosure', models.FileField(upload_to='static/admin/img')),
                ('disclosure_details', models.CharField(max_length=100)),
            ],
        ),
    ]
