# Generated by Django 5.0.1 on 2025-01-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0054_disclosure_regulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shareholding_Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareholding_pattern', models.FileField(upload_to='static/admin/img')),
                ('shareholding_pattern_details', models.CharField(max_length=100)),
            ],
        ),
    ]
