# Generated by Django 5.0.1 on 2025-01-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0055_shareholding_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_exchange', models.FileField(upload_to='static/admin/img')),
                ('stock_exchange_details', models.CharField(max_length=100)),
            ],
        ),
    ]
