# Generated by Django 5.0.1 on 2025-01-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0057_notice_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Press_Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('press_release', models.FileField(upload_to='static/admin/img')),
                ('press_release_details', models.CharField(max_length=100)),
            ],
        ),
    ]
