# Generated by Django 5.0.1 on 2025-01-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0058_press_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate_Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_social', models.FileField(upload_to='static/admin/img')),
                ('corporate_social_details', models.CharField(max_length=100)),
            ],
        ),
    ]
