# Generated by Django 5.0.1 on 2025-01-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0059_corporate_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports', models.FileField(upload_to='static/admin/img')),
                ('reports_details', models.CharField(max_length=100)),
            ],
        ),
    ]
