# Generated by Django 5.0.1 on 2025-01-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0060_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk_Policies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policies1', models.FileField(upload_to='static/admin/img')),
                ('policies1_details', models.CharField(max_length=100)),
            ],
        ),
    ]
