# Generated by Django 5.0.1 on 2025-01-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0062_post_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_documents', models.FileField(upload_to='static/admin/img')),
                ('material_documents_details', models.CharField(max_length=100)),
            ],
        ),
    ]
