# Generated by Django 5.0.1 on 2025-01-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0063_material_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipo_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipo_documents', models.FileField(upload_to='static/admin/img')),
                ('ipo_documents_details', models.CharField(max_length=100)),
            ],
        ),
    ]
